### ISSUE TITLE
👋Introduction

### ISSUE THREAD

**Issue by okjake** [GSG-K3/event-booker#100]
Hi all!

I'm Jake, a software engineer in Spain, and I'll be helping out with some code reviews and trying to make myself useful! Looks like you've made a great start, I'll try to check in roughly once a day and have a look at any open PRs, but feel free to request a review too if there's anything you're unsure about. 

You can (soon) get me on discord (Jake~) if you have any questions or would like to set up some time to chat more generally 🙂

**Comment by sara219** [comment]
Hi Jake 👋
It's great to have you here with us.
We will be lucky to learn from your experiences, and we are looking forward to your feedback and review

**Comment by YakoobHammouri** [comment]
Hi Jake 
Nice to join us
