### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by YakoobHammouri** [GSG-K3/event-booker#6]
![_Entity Relationship Diagram Example (UML Notation) (1)](https://user-images.githubusercontent.com/7718220/79760851-50c1d700-8329-11ea-8e29-f68bf086efe5.png)

**Comment by sara219** [comment]
![Entity_Relationship_Diagram_Example_UML_Notation_1](https://user-images.githubusercontent.com/47992412/79761058-a39b8e80-8329-11ea-8a3d-8166b3aaf1e3.png)
